.TH EP 1 "May 2014" "2.0.0" "User Commands"
.SH NAME
ep \- display television series episode information
.SH SYNOPSIS
.B ep
[-i] [\-\fBadrt\fR] [\-\fBs\fR\fIN\fR] [\-\fBe\fR\fIN\fR] \fITITLE\fR
.SH DESCRIPTION
.PP
Retrieve episode information about a TV series.
.PP
Mandatory arguments to long options are mandatory for short options too.
.TP
\fB\-s\fR, \fB\-\-season\fR=\fIN\fR
specify season \fIN\fR of \fITITLE\fR
.TP
\fB\-e\fR, \fB\-\-episode\fR=\fIN\fR
specify episode \fIN\fR of \fITITLE\fR
.TP
\fB\-a\fR, \fB\-\-air\fR
print air date for each episode
.TP
\fB\-d\fR, \fB\-\-description\fR
print description for each episode
.TP
\fB\-r\fR, \fB\-\-rating\fR
print rating for each episode
.TP
\fB\-t\fR, \fB\-\-no-title\fR
do not print episode titles
.TP
\fB\-i\fR, \fB\-\-info\fR
print general info about \fITITLE\fR
.TP
\fB\-h\fR, \fB\-\-help\fR
print help message and exit
.TP
\fB\-v\fR, \fB\-\-version\fR
print version info and exit
.SH "EXIT STATUS"
Returns zero on success, and non-zero if an error occurred.
.SH EXAMPLES
.nf
Print the titles of all episodes in the HBO series \fIThe Wire\fR:

    ep the wire

Print title, original air date, rating, and description of
season 2 episode 12 of \fIThe Wire\fR:

    ep -adr -s2 -e12 the wire
    ep --air --description --rating --season=2 --episode=12 the wire

Print rating of season 5 episode 14 of AMC's \fIBreaking Bad\fR:

    ep -r -s5 -e16 breaking bad

.SH AUTHOR
Written by Nathan Forbes.
.SH NOTES
All television data is obtained from <http://www.tv.com/>.
.SH "REPORTING BUGS"
Report bugs to sforbes41@gmail.com.
.SH COPYRIGHT
Copyright \(co 2014 Nathan Forbes.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
