.TH TVI 1 "May 2014" "2.6.0" "User Commands"
.SH NAME
tvi \- display information about a television series
.SH SYNOPSIS
.B tvi
[\-\fBadir\fR] [\-\fBs\fR\fIN\fR[,\fIN\fR,...]] [\-\fBe\fR\fIN\fR[,\fIN\fR,...]] \fITITLE\fR
.SH DESCRIPTION
.PP
Retrieve episode information about a TV series.
.PP
Mandatory arguments to long options are mandatory for short options too.
.TP
\fB\-s\fR, \fB\-\-season\fR=\fIN\fR
specify season(s) \fIN\fR of \fITITLE\fR
more than 1 season can be specified in a comma-separated list: \fIN1\fR,\fIN2\fR,\fIN3\fR,...
.TP
\fB\-e\fR, \fB\-\-episode\fR=\fIN\fR
specify episode(s) \fIN\fR of \fITITLE\fR
more than 1 episode can be specified in a comma-separated list: \fIN1\fR,\fIN2\fR,\fIN3\fR,...
.TP
\fB\-a\fR, \fB\-\-air\fR
print air date for each episode
.TP
\fB\-d\fR, \fB\-\-description\fR
print description for each episode
.TP
\fB\-r\fR, \fB\-\-rating\fR
print rating for each episode
.TP
\fB\-i\fR, \fB\-\-info\fR
print general info about \fITITLE\fR
.TP
\fB\-h\fR, \fB\-\-help\fR
print help message and exit
.TP
\fB\-v\fR, \fB\-\-version\fR
print version info and exit
.SH "EXIT STATUS"
Returns zero on success, and non-zero if an error occurred.
.SH EXAMPLES
.nf
Print the titles of all episodes in HBO's \fIThe Wire\fR:

    tvi the wire

Print original air date, rating, and description of
season 2 episode 12 of \fIThe Wire\fR:

    tvi -adr -s2 -e12 the wire
    tvi --air --description --rating --season=2 --episode=12 the wire

Print rating of season 5 episode 14 of AMC's \fIBreaking Bad\fR:

    tvi -r -s5 -e16 breaking bad

Print general info about HBO's \fIGame of Thrones\fR:

    tvi --info game of thrones

Print and ratings for episodes 5, 6 and 7 from season 4 of AMC's
\fIMad Men\fR:

    tvi -r -s4 -e5,6,7 mad men

Print and descriptions for episode 1 of seasons 1, 2 and 3 of Showtime's
\fIHomeland\fR:

    tvi -d -s1,2,3 -e1 homeland

.SH AUTHOR
Written by Nathan Forbes.
.SH NOTES
All television data is obtained from <http://www.tv.com/>.
.SH "REPORTING BUGS"
Report bugs to sforbes41@gmail.com.
.SH COPYRIGHT
Copyright \(co 2014 Nathan Forbes.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
